### ISSUE TITLE
LIVE-FLV 状态延迟较大，建议初始状态默认为”loading...“中

### ISSUE THREAD

**Issue by huzunjie** [Chimeejs/chimee-plugin-center-state#1]
参见官网的LIVE-FLV示例： http://chimee.org/ ，Kernel 拉FLV到通过MSE塞给video需要一些时间（可能要几秒或十几秒不等），这期间video的src为空--- 不会触发原生的 loadstart事件，目前的逻辑不显示loading，看起来像是异常卡住的状态...
![image](https://user-images.githubusercontent.com/3885060/32366739-795deb6e-c04d-11e7-8a4a-e66b604ec879.png)

**Comment by songguangyu** [comment]
kernel 有load 方法，由chimee层决定何时来调用load 这块是否应该由chimee 来包装一下! @toxic-johann

**Comment by songguangyu** [comment]
并且延迟大到几秒 十几秒的话 建议和服务端跟进一下。

**Comment by huzunjie** [comment]
chimee包装也不太好，会有FLV处理和HLS不一致的问题；针对这个问题，在UI插件层调整loading展示逻辑比较合理 ---- 改“等待loadstart后才显示loading”为“判断是否有传入src,如果有则默认显示loading，开播或异常后切换到相应状态”比较合理。

**Comment by toxic-johann** [comment]
@huzunjie @songguangyu 同意由插件层进行更改。这样比较合理。 chimee 层不处理。

**Comment by yandeqiang** [comment]
已经更新为， 默认显示 loading。
