### ISSUE TITLE
关于图标替换API等需求

### ISSUE THREAD

**Issue by skyline0705** [Chimeejs/chimee-plugin-center-state#2]
麻烦问一下，后期是否有考虑对chimee-plugin-center-state像chimee-plugin-controlbar一样支持外部传入图标？目前方式看了一下代码貌似仍然只能通过全局覆写样式魔改解决~

谢谢~

**Comment by yandeqiang** [comment]
嗯。 这个图标传入方式，下次会做一定的改版。
